"""Frozen constants for the approved RLOO-DAPO-T1.2-KV Spec v2 run."""

from __future__ import annotations

from pathlib import Path
from types import MappingProxyType

from ksllm4rec_rloo import contract as legacy


SCHEMA_VERSION = 1
SPEC_VERSION = "RLOO-DAPO-T1.2-KV-v2"
PROFILE = "frontier_sft_epoch2_lora64_rloo_dapo_t12_k1_kvcache"

PROJECT_ROOT = legacy.PROJECT_ROOT
BASE_MODEL = legacy.BASE_MODEL
SFT_ADAPTER = legacy.SFT_ADAPTER
TOKENIZER = legacy.TOKENIZER
SOURCE_DATA = legacy.SOURCE_DATA
PROVENANCE = legacy.PROVENANCE
GROUPS_DIR = legacy.GROUPS_DIR
TRIE_DIR = legacy.TRIE_DIR
FIXED_PROBE = legacy.FIXED_PROBE

BASE_MODEL_SHA256 = legacy.BASE_MODEL_SHA256
SFT_ADAPTER_SHA256 = legacy.SFT_ADAPTER_SHA256
SFT_CONFIG_SHA256 = legacy.SFT_CONFIG_SHA256
TOKENIZER_SHA256 = legacy.TOKENIZER_SHA256
SOURCE_DATA_SHA256 = legacy.SOURCE_DATA_SHA256
PROVENANCE_SHA256 = legacy.PROVENANCE_SHA256
GROUPS_SHA256 = legacy.GROUPS_SHA256
TRIE_MANIFEST_SHA256 = legacy.TRIE_MANIFEST_SHA256
FIXED_PROBE_SHA256 = legacy.FIXED_PROBE_SHA256

EXPECTED_SOURCE_ROWS = legacy.EXPECTED_SOURCE_ROWS
EXPECTED_RECOMMEND_ROWS = legacy.EXPECTED_RECOMMEND_ROWS
EXPECTED_RECOMMEND_GROUPS = legacy.EXPECTED_RECOMMEND_GROUPS
EXPECTED_POSITIVE_EDGES = legacy.EXPECTED_POSITIVE_EDGES
EXPECTED_UNIQUE_POSITIVE_SIDS = legacy.EXPECTED_UNIQUE_POSITIVE_SIDS
EXPECTED_TRIE_LEAVES = legacy.EXPECTED_TRIE_LEAVES
EXPECTED_DOMAIN_A_NODES = legacy.EXPECTED_DOMAIN_A_NODES
EXPECTED_DOMAIN_AB_NODES = legacy.EXPECTED_DOMAIN_AB_NODES

POLICY_ADAPTER = legacy.POLICY_ADAPTER
LORA_RANK = legacy.LORA_RANK
LORA_ALPHA = legacy.LORA_ALPHA
LORA_DROPOUT = legacy.LORA_DROPOUT
LORA_TARGET_MODULES = legacy.LORA_TARGET_MODULES

GROUP_SIZE = 16
PROMPT_BATCH_SIZE = 8
MAX_ACTIVE_SEQUENCES = 16
CANDIDATES_PER_PROMPT_WAVE = 2
LOSS_CHUNK_SIZE = 8
EFFECTIVE_GROUPS_PER_WINDOW = 32
MINIBATCH_GROUPS = 8
OPTIMIZER_UPDATES_PER_WINDOW = 4
NUM_ITERATIONS = 1

TEMPERATURE = 1.2
CLIP_RATIO_LOW = 0.8
CLIP_RATIO_HIGH = 1.28
SAMPLE_CANONICAL_MAX_LOGP_DIFF = 5.0e-3
CANONICAL_REPLAY_MAX_LOGP_DIFF = 1.0e-5

REWARD_VALUES = MappingProxyType(
    {
        "exact": 1.0,
        "same_ab": 0.40,
        "same_a": 0.15,
        "same_domain": 0.01,
        "other_domain": 0.0,
    }
)

EFFECTIVE_EPOCHS = 2
WINDOWS_PER_EFFECTIVE_EPOCH = 532
TOTAL_WINDOWS = EFFECTIVE_EPOCHS * WINDOWS_PER_EFFECTIVE_EPOCH
TOTAL_OPTIMIZER_UPDATES = TOTAL_WINDOWS * OPTIMIZER_UPDATES_PER_WINDOW
LEARNING_RATE = 1.0e-6
WARMUP_WINDOWS = 10
MAX_GRAD_NORM = 1.0

KV_CACHE_BUDGET_GIB = 12.0
MAX_RESERVED_GIB = 20.0
MODEL_NUM_LAYERS = 28
MODEL_NUM_KV_HEADS = 8
MODEL_HEAD_DIM = 128
MODEL_CACHE_DTYPE_BYTES = 2
MAX_COMPLETION_LENGTH = 32
MAX_OBSERVED_PROMPT_LENGTH = 2_929

RUN_DIR = Path(
    PROJECT_ROOT
    / "artifacts/rloo/runs/frontier_sft_epoch2_lora64_rloo_dapo_t12_k1_kvcache_2epoch"
)
LOG_DIR = Path(
    PROJECT_ROOT
    / "operation_logs/rloo/frontier_sft_epoch2_lora64_rloo_dapo_t12_k1_kvcache_v2"
)
